services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shop_tes_app
    ports:
      - "8080:80"
    volumes:
      - /var/www/shop-tes:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: shop_tes_db
    environment:
      MYSQL_DATABASE: catalog_test
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "33061:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d:ro

volumes:
  db_data: